#!/bin/bash
#
# dem2tga
#
# Description:
#     Takes a given DEM file and runs it in a Source Engine game. Utilises the
#     built in console commands to load up the DEM file, export every frame to
#     TGA, as well as sound being exported to stereo WAV. Then, the files
#     exported are used to generate a preview MP4 file for use in Adobe After
#     Effects to ensure proper alignment of all 4 POVs.
#
#     When specifying "dem_path", it is relative to the game's "mod_dir", just
#     like what Source Engine demands.
#
#     Just a heads up, in case it wasn't already obvious, we're dealing with
#     raw files here. You will need a shitload of space. At least 1 TB free
#     should suffice for most cases.
#
# Author:
#     Clara Nguyen (@iDestyKK)
#

# -----------------------------------------------------------------------------
# Initialise                                                               {{{1
# -----------------------------------------------------------------------------

# Argument Check
if [ $# -ne 4 ]; then
	printf "usage: %s game_exe mod_dir dem_path local_dir\n" "$0"
	exit 1
fi

# Where are we...?
SCRIPT=$(readlink -f "$0")
SPATH=$(dirname "$SCRIPT")

# Generate movie path
TMP_DIR="${SPATH}/$4"

if [ -d "$TMP_DIR" ]; then
	rm -rf "$TMP_DIR"
fi

mkdir "$TMP_DIR"

MOV_PATH=$(\
	echo "$TMP_DIR" \
	| sed 's/^\/\([^\/]*\)\//\U\1\E:\//' \
	| sed 's/\//\\/g'\
)

# -----------------------------------------------------------------------------
# Source Engine CFG Generate                                               {{{1
# -----------------------------------------------------------------------------

# Export a configuration file to the game's mod_dir with commands
echo "//Generated by dem2tga. Do not modify." \
	> "$2/cfg/__dem2tga.cfg"

echo ""                                >> "$2/cfg/__dem2tga.cfg"
echo "//Enable Cheats"                 >> "$2/cfg/__dem2tga.cfg"
echo "sv_cheats 1"                     >> "$2/cfg/__dem2tga.cfg"
echo ""                                >> "$2/cfg/__dem2tga.cfg"
echo "//Graphic Configuration"         >> "$2/cfg/__dem2tga.cfg"
echo "mat_fastspecular 0"              >> "$2/cfg/__dem2tga.cfg"
echo "r_waterforcereflectentities 1"   >> "$2/cfg/__dem2tga.cfg"
echo "cl_interp 0.015"                 >> "$2/cfg/__dem2tga.cfg"
echo "cl_interp_ratio 1"               >> "$2/cfg/__dem2tga.cfg"
echo "mat_picmip -10"                  >> "$2/cfg/__dem2tga.cfg"
echo "host_framerate 60"               >> "$2/cfg/__dem2tga.cfg"
echo ""                                >> "$2/cfg/__dem2tga.cfg"
echo "//Start Demo Playback"           >> "$2/cfg/__dem2tga.cfg"
echo "demo_quitafterplayback 1"        >> "$2/cfg/__dem2tga.cfg"
echo "startmovie \"$MOV_PATH\\frame\"" >> "$2/cfg/__dem2tga.cfg"
echo "playdemo \"$3\""                 >> "$2/cfg/__dem2tga.cfg"

# -----------------------------------------------------------------------------
# Run Game                                                                 {{{1
# -----------------------------------------------------------------------------

# Run... duh
"$1" -game "$(basename "$2")" -novid +exec "__dem2tga.cfg"

# Cleanup the cfg file
rm "$2/cfg/__dem2tga.cfg"

# -----------------------------------------------------------------------------
# Generate additional files                                                {{{1
# -----------------------------------------------------------------------------

#
# Generate the preview MP4 that is to be loaded into After Effects to ensure
# all POVs are perfectly aligned.
#

ffmpeg \
	-r       60                         \
	-i       "${TMP_DIR}/frame%04d.tga" \
	-i       "${TMP_DIR}/frame.wav"     \
	-r       60                         \
	-c:v     libx264                    \
	-c:a     aac                        \
	-pix_fmt yuv420p                    \
	-preset  ultrafast                  \
	"${TMP_DIR}/preview.mp4"

#
# Also generate a FLAC of the audio. This can be replaced with a 7.1 version
# for use in encode.sh if needed.
#

ffmpeg \
	-i "${TMP_DIR}/frame.wav" \
	-compression_level 12     \
	"${TMP_DIR}/frame.flac"

rm "${TMP_DIR}/frame.wav"
